import { describe, expect, it } from "vitest";
// The frontend has no Node typings (tsc -b checks test files too), so the page comes in with Vite's ?raw import.
import page from "../../public/about/index.html?raw";
import home from "../../index.html?raw";

// /about/ is generated by scripts/generate-about-page.mjs. These checks read the committed page the way a crawler would:
// the visible FAQ must equal the FAQPage structured data, and the page may only point at the home page's one
// SoftwareApplication (by @id), never define a second one.

const unesc = (s: string) => s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&amp;/g, "&");

function visibleFaq(): Array<{ q: string; a: string }> {
  return [...page.matchAll(/<details class="faq[^"]*">\s*<summary><span class="q">([\s\S]*?)<\/span><\/summary>\s*<p class="a">([\s\S]*?)<\/p>\s*<\/details>/g)].map((m) => ({
    q: unesc(m[1]),
    a: unesc(m[2]),
  }));
}

function blocks(html: string): Array<Record<string, unknown>> {
  return [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map((m) => JSON.parse(m[1]));
}

describe("About page FAQ", () => {
  const visible = visibleFaq();
  const graph = (blocks(page)[0]["@graph"] as Array<Record<string, unknown>>) ?? [];
  const faqNode = graph.find((n) => n["@type"] === "FAQPage") as { mainEntity: Array<{ name: string; acceptedAnswer: { text: string } }> };

  it("uses native details/summary, one per question, closed by default so it works without JavaScript", () => {
    expect(visible).toHaveLength(5);
    expect((page.match(/<details /g) ?? []).length).toBe(5);
    expect(page).not.toMatch(/<details[^>]*\sopen/);
    expect(page).not.toMatch(/<script(?![^>]*application\/ld\+json)[^>]*>\s*[^<\s]/); // no inline scripts (the site CSP blocks them)
  });

  it("visible questions and answers equal the FAQPage structured data, word for word, in the same order", () => {
    expect(faqNode.mainEntity.map((e) => ({ q: e.name, a: e.acceptedAnswer.text }))).toEqual(visible);
  });

  it("every answer is 40 to 70 words", () => {
    for (const { q, a } of visible) {
      const words = a.trim().split(/\s+/).length;
      expect(words, q).toBeGreaterThanOrEqual(40);
      expect(words, q).toBeLessThanOrEqual(70);
    }
  });

  it("does not ask about a browser extension, which is not published or offered anywhere", () => {
    expect(page.toLowerCase()).not.toContain("extension");
  });
});

describe("About page head and copy", () => {
  it("is plain ASCII with no em or en dash anywhere", () => {
    expect(/[^\x00-\x7F]/.test(page)).toBe(false);
    expect(/[–—]/.test(page)).toBe(false);
    expect(page).not.toMatch(/&[mn]dash;/);
  });

  it("has a canonical link, the robots meta, og and twitter tags", () => {
    expect(page).toContain('<link rel="canonical" href="https://lazyrelay.com/about/" />');
    expect(page).toContain('content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"');
    for (const tag of ["og:title", "og:description", "og:url", "og:image", "twitter:card", "twitter:title"]) expect(page, tag).toContain(tag);
  });

  it("carries one structured data block that references the home page SoftwareApplication by @id and defines none", () => {
    const all = blocks(page);
    expect(all).toHaveLength(1);
    const text = JSON.stringify(all[0]);
    expect(text).not.toContain('"SoftwareApplication"');
    expect(text).toContain('"about":{"@id":"https://lazyrelay.com/#software"}');
    expect(home).toContain('"@id": "https://lazyrelay.com/#software"');
  });

  it("states the operator and contacts exactly as the Privacy page does", () => {
    expect(page).toContain("IPE Projects (Pty) Ltd");
    expect(page).toContain("2021/003176/07");
    for (const mail of ["hello@lazyrelay.com", "support@lazyrelay.com", "accounts@lazyrelay.com"]) expect(page).toContain(mail);
  });

  it("makes no ranking, uncapped or military-grade claim", () => {
    const lower = page.replace(/<(style|script)[\s\S]*?<\/\1>/g, " ").toLowerCase(); // copy only, not CSS colour codes
    for (const bad of ["#1", "best ", "fastest", "100%", "uncapped", "military", "zero visibility", "guarantee"]) expect(lower.includes(bad), bad).toBe(false);
  });
});
